---
- name: Ensures traefik dir exists
  file:
    path: "{{ traefik_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Ensures acme.json file exists
  file:
    path: "{{ traefik_dir }}/acme.json"
    state: touch
    mode: 0600
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Create traefik/docker-compose.yml
  template:
    dest: "/home/{{ user }}/docker-compose.yml"
    force: true
    src: templates/docker-compose.yml.j2
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Create etc/docker/daemon.json
  template:
    dest: "/etc/docker/daemon.json"
    force: true
    src: templates/daemon.json.j2
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Restart Docker service
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: Run docker-compose up -d
  shell: "cd /home/{{ user }} && docker-compose up -d"
